name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: /opt/hostedtoolcache/go/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install dependencies
        env: 
          GO111MODULE: "on"
        run: |
          go install -v honnef.co/go/tools/cmd/staticcheck@latest

      - name: Show versions
        run: |
          go version

      - name: Vet
        run: |
          go vet ./...

      - name: Staticcheck
        run: |
          staticcheck ./...

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        run: |
          go build -v ./...
