name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build 
    strategy:
      matrix:
        go: [1.19, 1.20]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Show versions
        run: |
          go version

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        run: |
          go mod vendor
          go build -v ./...
